# Generated by Django 3.2.9 on 2021-11-29 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, default='old@gmail.com', max_length=254, unique=True)),
                ('method', models.TextField(null=True)),
                ('password', models.BinaryField(null=True)),
                ('device_id', models.TextField(null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(blank=True, null=True)),
                ('dt_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('session_expiry_date', models.DateTimeField()),
                ('dt_created', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 57, 20, 778010))),
                ('dt_updated', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 57, 20, 778010))),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiohttpServer.users')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
