# Generated by Django 3.2.9 on 2021-12-21 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiohttpServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='dt_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 19, 8, 35, 509558)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='dt_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 19, 8, 35, 509558)),
        ),
    ]
