# Generated by Django 3.2.9 on 2021-12-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiohttpServer', '0002_auto_20211221_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sessions',
        ),
    ]
